git:
  depth: 10

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '6'

install:
  - npm install

script:
  - npm run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
